name: Deploy to Production

on:
  push:
    branches:
      - main
      - ci-cd-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H reptracker.duckdns.org >> /home/runner/.ssh/known_hosts

      - name: Run deploy script
        run: ssh -o StrictHostKeyChecking=no deploy@reptracker.duckdns.org "cd ~/RepTracker && ./deploy.sh"
