name: Deploy to Production

on:
  push:
    branches:
      - main
      - ci-cd-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        shell: bash
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.DEPLOY_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan -H reptracker.duckdns.org >> "$HOME/.ssh/known_hosts"

      - name: Run deploy script
        shell: bash
        run: ssh -o StrictHostKeyChecking=no deploy@reptracker.duckdns.org "cd ~/RepTracker && ./deploy.sh"
